% Interface to info space. Modes that call info functions should begin by 
% calling info_mode() to load info.sl.
implements("info");
define add_bookmark();
define find_dir();
define follow_current_xref();
define follow_menu();
define follow_reference();
define goto_last_position();
define goto_next_position();
define goto_node();
define goto_stack_position();
define info_extract_pointer();
define info_extract_pointer();
define info_find_node_split_file();
define info_find_node_this_file();
define info_find_menu();
define info_find_file();
define info_is_compressed();
define info_looking_at();
define info_make_file_name();
define info_narrow();
define info_next();
define info_push_position();
define info_prev();
define info_record_position();
define info_search_marker();
define info_top();
define info_up();
define make_unzip_cmd();
define menu();
define menu_number();
define mouse_hook();
define next_up();
define next_up();
define next_xref();
define prev_xref();
define quick_help();
define quit();
define scroll();
define tutorial();
provide("infospace");
